Draft: added support for unknown-length track
InputUsername/rescrobbled pull request #53
Opened 2021-12-19 22:25 UTC by marius851000

It basically default to 30 seconds track, and so will be added after 15 second of listen. Draft as I haven't tested this at all (outside of static checks), will confirm once I'm able to do so.

2021-12-20 16:55 UTC, InputUsername requested changes
Thanks! Could you please make the PR against the `development` branch? master is slightly out of date (my bad for not making this clearer in the readme)

2021-12-20 16:55 UTC, InputUsername commented on src/mainloop.rs
> +        let length = metadata.length();
Could this be replaced by something like `let length = metadata.length().unwrap_or(MIN_LENGTH)` ? Not sure if that would work, but it would avoid having to unwrap later.

2021-12-21 07:09 UTC, marius851000 commented on src/mainloop.rs
> +        let length = metadata.length();
Well... That would risk to cause confusion with music that actually are exactly MIN_LENGTH (do they exist ? probably not). I use it whether it's something to not use the branch that get the Duration of the song.

2021-12-21 07:11 UTC, marius851000 commented
Here it is. It should actually work now. One issue I found out however is that when I pause the radio, then restart it, it add the music twice. I should check to see if the music hasn't already been pushed recently before re-using it.

2021-12-22 18:48 UTC, InputUsername commented
Thanks, looks good! I will have a closer look later this week when I have more time.

2021-12-24 11:11 UTC, InputUsername requested changes
Looks good! Some small changes and then I'll merge it.

2021-12-24 11:11 UTC, InputUsername commented on src/mainloop.rs
> +        let length = if let Some(lenght) = metadata.length() {
Typo? (`lenght` -> `length`)

2021-12-24 11:11 UTC, InputUsername commented on src/mainloop.rs
> +            } else if length.map(|length| length < current_play_time).unwrap_or(false) {
I'd say `current_play_time >= length` is more natural.

2022-01-01 23:38 UTC, InputUsername commented
Thanks for the PR @marius851000! This will be in the `v0.5.0` release!

2022-01-01 23:38 UTC, merged